### ISSUE TITLE
order-properties output is malformed

### ISSUE THREAD

**Issue by gabegorelick** [JoshuaKGoldberg/eslint-plugin-package-json#10] opened 2020-10-05 14:20 UTC
The `order-properties` rule uses the `disparity` module to provide styled output. However, `disparity` uses terminal escape characters that are problematic. For one, the ESC characters used lead to invalid XML when generating results in junit format. But even the default text output doesn't seem to work in all terminals:
![image](https://user-images.githubusercontent.com/610129/95090956-dd076100-06f3-11eb-9a44-162e32cb4ea3.png)

I'm not aware of any eslint rules that attempt to display a diff like this. Perhaps the output could be something like "the order of properties should be x, y, z" or "dependencies should be alphabetized." I'm not sure the minutiae of which exact line is in error really matters, since if there's any error users will probably just use --fix.

**Comment by JoshuaKGoldberg** [comment] 2023-09-13 01:50
Hmm, I don't reproduce this issue with VS Code 1.82.0 and zsh 5.8.1 on macOS Ventura 13.2. What shell/terminal/etc are you using @gabegorelick (if you're still interested in this ~3 years later)?

Agreed that it's quite unusual to list the diff like this - especially since it should be resolved in `--fix` mode. Maybe it'd be better to give a general error the way https://github.com/lydell/eslint-plugin-simple-import-sort does?

**Comment by JoshuaKGoldberg** [comment] 2023-10-17 21:53
I ended up removing the diff in #40. The `0.3.x` line shouldn't experience this bug anymore. Cheers!

**Closed by JoshuaKGoldberg** 2023-10-17 21:53 UTC
Labels: bug, status: in discussion
