### ISSUE TITLE
🐛 Bug: Can not import this in ESM package

### ISSUE THREAD

**Issue by hyoban** [JoshuaKGoldberg/eslint-plugin-package-json#152] opened 2024-02-17 10:59 UTC
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

No error with flat config

### Actual

```
TypeError: Cannot read properties of undefined (reading 'docs')
```

### Additional Info

Related: #91 

If you use this plugin like this:

```js
import * as pluginPackageJson from 'eslint-plugin-package-json'

{
  files: ['package.json'],
  plugins: {
    'package-json': pluginPackageJson,
  },
  rules: pluginPackageJson.configs.recommended.rules,
},
```

You will get an error, because flat config use esm. But in `lib/index.mjs`, it always use default import from a cjs file.

https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/blob/baf1aaa2696c3da4634f21f0d091669b3d3fb97d/src/index.ts#L1-L9

The imported `validVersion` looks like

```
{
  "default": {
    "meta": {
      "docs": {
        "category": "Best Practices",
        "description": "Enforce that package versions are valid semver specifiers",
        "recommended": true
      },
      "hasSuggestions": true,
      "messages": {
        "invalid": "Version is not a valid semver specifier.",
        "type": "\"version\" should be a string."
      }
    }
  }
}
```

So `rule.meta` is `undefined`

https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/blob/baf1aaa2696c3da4634f21f0d091669b3d3fb97d/src/index.ts#L26-L28

**Comment by JoshuaKGoldberg** [comment] 2024-02-17 15:01
Duplicate of #91. Accepting PRs!

**Comment by JoshuaKGoldberg** [comment] 2024-02-20 13:34
Continuing conversation from https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/pull/157#discussion_r1495268752: this isn't a duplicate of #92 after all.

The problem is that the source code default-imports internally a whole bunch:

https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/blob/6e8b6fbe777d03731f5552c980eaad4e5f8d4dad/src/index.ts#L1-L2

Switching from default exports `export default ...` to named exports (`export const ... = ...`) fixes it. Accepting PRs!

Note that the strategy in #157 of moving to `type: module` isn't the right fix here, I don't think. This plugin still needs to work for CommonJS consumers for the time being - such as legacy ESLint config setups.

**Comment by hyoban** [comment] 2024-02-20 13:38
Moving to `type: module` still supports legacy ESLint config. I published a test version package `@hyoban/eslint-plugin-package-json`, you can give it a try.

**Closed** 2024-02-20 14:49 UTC
Labels: type: bug, status: accepting prs

**Comment by JoshuaKGoldberg** [comment] 2024-02-20 14:53
@allcontributors add @hyoban for ideas

😁
